/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.1.119 */
/* Module Version: 5.4 */
/* Mon Aug 21 18:36:19 2017 */

/* parameterized module instance */
JBBoot __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
