-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.1.119
-- Module  Version: 6.5
-- Sat Jun 10 22:07:20 2017

-- parameterized module component declaration
component hdmi_upscale_buffer
    port (WrAddress: in  std_logic_vector(12 downto 0); 
        RdAddress: in  std_logic_vector(12 downto 0); 
        Data: in  std_logic_vector(5 downto 0); WE: in  std_logic; 
        RdClock: in  std_logic; RdClockEn: in  std_logic; 
        Reset: in  std_logic; WrClock: in  std_logic; 
        WrClockEn: in  std_logic; Q: out  std_logic_vector(5 downto 0));
end component;

-- parameterized module component instance
__ : hdmi_upscale_buffer
    port map (WrAddress(12 downto 0)=>__, RdAddress(12 downto 0)=>__, 
        Data(5 downto 0)=>__, WE=>__, RdClock=>__, RdClockEn=>__, Reset=>__, 
        WrClock=>__, WrClockEn=>__, Q(5 downto 0)=>__);
