-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.7.1.502
-- Module  Version: 1.6
-- Fri May 06 16:05:34 2016

-- parameterized module component declaration
component sintable
    port (Clock: in  std_logic; ClkEn: in  std_logic; 
        Reset: in  std_logic; Theta: in  std_logic_vector(7 downto 0); 
        Sine: out  std_logic_vector(15 downto 0); 
        Cosine: out  std_logic_vector(15 downto 0));
end component;

-- parameterized module component instance
__ : sintable
    port map (Clock=>__, ClkEn=>__, Reset=>__, Theta(7 downto 0)=>__, 
        Sine(15 downto 0)=>__, Cosine(15 downto 0)=>__);
